# AO Chef Cookbooks CI/CD Pipeline
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# CI Trigger
trigger:
- master

# PR Trigger
pr:
- master

pool:
  name: 'TFE-Build-Agents'

# Add the test-kitchen pipeline variable group
variables:
- group: test-kitchen

steps:

# Add git config for build agent to pull other ao cookbooks from Azure DevOps
- task: CmdLine@2
  displayName: 'Add Git Credentials'
  inputs:
    script: 'git config --global http.extraheader "AUTHORIZATION: bearer $(System.AccessToken)"'

- powershell: |
    Write-Host "##vso[task.prependpath]C:\opscode\chef-workstation\bin"
    Write-Host "##vso[task.prependpath]C:\opscode\chef-workstation\embedded\bin"
  displayName: 'Set PATH'

- powershell: |
    chef env --chef-license accept
  displayName: 'CHEF Environment'

- powershell: |
    cookstyle .
  displayName: 'COOKSTYLE Syntax & Linting Tests'

- task: vsts-chef-task-test-kitchen@1
  inputs:
    tkAzureEndpoint: 'Chef-Test-Kitchen'
    # Always clean up resource group contents, even on failing Test Kitchen run
    # change to back to default of "passing" if failed instances need investigated
    # https://docs.chef.io/ctl_kitchen.html#id29 
    tkCommand: 'test --destroy always'
    tkKitchenFile: 'kitchen.yml'

# Need to always unset git credentials as they expire
- task: CmdLine@2
  displayName: 'Cleanup Git Credentials'
  inputs:
    script: 'git config --global --unset http.extraheader'
  condition: always()
